export const FETCH_RENTALS = "FETCH_RENTALS";
export const FETCH_RENTALS_SUCCESS = "FETCH_RENTALS_SUCCESS";
export const FETCH_RENTAL_BY_ID_START = "FETCH_RENTAL_BY_ID_START";
export const FETCH_RENTAL_BY_ID_SUCCESS = "FETCH_RENTAL_BY_ID_SUCCESS";
